# Generated by Django 3.2.15 on 2022-08-11 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20220811_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='time_to_cook',
            field=models.IntegerField(choices=[(5, '5 Minutes'), (10, '10 Minutes'), (15, '15 Minutes'), (20, '20 Minutes'), (25, '25 Minutes'), (30, '30 Minutes'), (40, '40 Minutes'), (50, '50 Minutes'), (60, '60 Minutes')], default=5),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='time_to_prepare',
            field=models.IntegerField(choices=[(5, '5 Minutes'), (10, '10 Minutes'), (15, '15 Minutes'), (20, '20 Minutes'), (25, '25 Minutes'), (30, '30 Minutes'), (40, '40 Minutes'), (50, '50 Minutes'), (60, '60 Minutes')], default=5),
        ),
    ]
